package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"
)

const projectIgnore = `# sandcode runtime artifacts
work/
store.db
`

// dockerfileTemplate is the base Dockerfile rendered with selected agents.
// Each entry below is a stanza that gets concatenated when its agent is enabled.
type langProfile struct {
	name     string
	baseFrom string
	apt      []string
}

var langProfiles = map[string]langProfile{
	"node":   {"node", "node:20-bookworm-slim", nil},
	"python": {"python", "python:3.12-slim-bookworm", []string{"build-essential"}},
	"go":     {"go", "golang:1.23-bookworm", nil},
	"rust":   {"rust", "rust:1-bookworm", []string{"build-essential"}},
	"polyglot": {"polyglot", "node:20-bookworm-slim", []string{
		"python3", "python3-pip", "python3-venv",
		"golang-go",
	}},
}

type agentInstall struct {
	cli    string
	stanza string
}

var agentInstalls = map[string]agentInstall{
	"claude-code": {
		cli: "claude",
		stanza: `# Install Claude Code CLI. ~/.claude is bind-mounted at runtime.
RUN npm install -g @anthropic-ai/claude-code
`,
	},
	"codex": {
		cli: "codex",
		stanza: `# Install Codex CLI. OPENAI_API_KEY is injected at runtime.
RUN npm install -g @openai/codex
`,
	},
	"cursor": {
		cli: "cursor-agent",
		stanza: `# Install cursor-agent CLI. CURSOR_API_KEY is injected at runtime.
RUN curl -fsSL https://cursor.com/install.sh | bash
ENV PATH=/root/.cursor/bin:${PATH}
`,
	},
}

// renderDockerfile returns a complete Dockerfile string for the chosen lang
// profile and selected agent CLIs.
func renderDockerfile(lang string, agents []string) string {
	prof, ok := langProfiles[lang]
	if !ok {
		prof = langProfiles["node"]
	}
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by `sandcode init` — extend with project-specific tools.\nFROM %s\n\n", prof.baseFrom)

	apt := append([]string{"git", "curl", "ca-certificates", "jq"}, prof.apt...)
	sort.Strings(apt)
	fmt.Fprintf(&b, "RUN apt-get update && apt-get install -y --no-install-recommends \\\n    %s \\\n && rm -rf /var/lib/apt/lists/*\n\n", strings.Join(apt, " "))

	// node-based images already have npm; non-node images need it for npm-based agents.
	hasNpm := strings.HasPrefix(prof.baseFrom, "node:")
	needsNpm := false
	for _, a := range agents {
		if a == "claude-code" || a == "codex" {
			needsNpm = true
		}
	}
	if needsNpm && !hasNpm {
		b.WriteString("# Add Node for npm-based agent CLIs.\nRUN apt-get update && apt-get install -y --no-install-recommends nodejs npm \\\n && rm -rf /var/lib/apt/lists/*\n\n")
	}

	for _, name := range agents {
		if a, ok := agentInstalls[name]; ok {
			b.WriteString(a.stanza)
			b.WriteString("\n")
		}
	}
	b.WriteString("WORKDIR /workspace\n")
	return b.String()
}

func renderConfig(lang, sandbox, defaultAgent, strategy string) string {
	return fmt.Sprintf(`# .sandcode/config.yaml — project-level defaults.
# All keys here can be overridden by CLI flags.
project:
  language: %s

sandbox:
  provider: %s
  image: sandcode-default:latest
  workdir: /workspace
  network: bridge
  limits:
    cpus: "2"
    memory: "4g"

agent:
  default: %s

git:
  strategy: %s

auth:
  mode: bindmount
`, lang, sandbox, defaultAgent, strategy)
}

func newInitCmd() *cobra.Command {
	var (
		nonInteractive bool
		flagLang       string
		flagAgents     []string
		flagSandbox    string
		flagStrategy   string
		flagOverwrite  bool
	)

	cmd := &cobra.Command{
		Use:   "init",
		Short: "Scaffold a .sandcode/ directory in the current project",
		RunE: func(cmd *cobra.Command, args []string) error {
			cwd, err := os.Getwd()
			if err != nil {
				return err
			}
			dir := filepath.Join(cwd, ".sandcode")
			if err := os.MkdirAll(dir, 0o755); err != nil {
				return err
			}

			lang := flagLang
			agents := flagAgents
			sandboxKind := flagSandbox
			strategy := flagStrategy

			if !nonInteractive {
				detected := detectLanguage(cwd)
				lang = ask("Project language", detected, []string{"node", "python", "go", "rust", "polyglot"})
				agentList := strings.Split(ask("Agents to bake into the image (comma-separated)", "claude-code", nil), ",")
				agents = nil
				for _, a := range agentList {
					a = strings.TrimSpace(a)
					if a != "" {
						agents = append(agents, a)
					}
				}
				sandboxKind = ask("Sandbox runtime", "docker", []string{"docker", "podman"})
				strategy = ask("Default git strategy", "merge-to-head", []string{"merge-to-head", "branch"})
			}

			if lang == "" {
				lang = "node"
			}
			if len(agents) == 0 {
				agents = []string{"claude-code"}
			}
			if sandboxKind == "" {
				sandboxKind = "docker"
			}
			if strategy == "" {
				strategy = "merge-to-head"
			}

			files := map[string]string{
				"Dockerfile":  renderDockerfile(lang, agents),
				"config.yaml": renderConfig(lang, sandboxKind, agents[0], strategy),
				".gitignore":  projectIgnore,
			}
			for name, body := range files {
				path := filepath.Join(dir, name)
				if _, err := os.Stat(path); err == nil && !flagOverwrite {
					fmt.Printf("skip   %s (already exists; pass --overwrite to replace)\n", path)
					continue
				}
				if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
					return err
				}
				fmt.Printf("create %s\n", path)
			}
			fmt.Println()
			fmt.Println("Next:")
			fmt.Printf("  1. Build the sandbox image:\n       %s build -t sandcode-default:latest .sandcode\n", sandboxKind)
			fmt.Printf("  2. Run an agent:\n       sandcode run \"add a hello world function\"\n")
			return nil
		},
	}
	cmd.Flags().BoolVar(&nonInteractive, "non-interactive", false, "skip prompts (use --lang/--agents/--sandbox/--strategy)")
	cmd.Flags().StringVar(&flagLang, "lang", "", "project language: node|python|go|rust|polyglot")
	cmd.Flags().StringSliceVar(&flagAgents, "agents", nil, "agents to bake into the image (claude-code,codex,cursor)")
	cmd.Flags().StringVar(&flagSandbox, "sandbox", "", "default sandbox: docker|podman")
	cmd.Flags().StringVar(&flagStrategy, "strategy", "", "default git strategy: merge-to-head|branch")
	cmd.Flags().BoolVar(&flagOverwrite, "overwrite", false, "replace existing files in .sandcode/")
	return cmd
}

// ask prompts the user with a default and (optional) suggestions list. Empty
// input returns the default. We keep it tiny and stdin-only — no fancy TUI.
func ask(label, def string, choices []string) string {
	prompt := label
	if len(choices) > 0 {
		prompt += " (" + strings.Join(choices, "/") + ")"
	}
	if def != "" {
		prompt += " [" + def + "]"
	}
	prompt += ": "
	fmt.Print(prompt)
	r := bufio.NewReader(os.Stdin)
	line, err := r.ReadString('\n')
	if err != nil {
		return def
	}
	line = strings.TrimSpace(line)
	if line == "" {
		return def
	}
	return line
}

// detectLanguage inspects cwd for common manifest files to suggest a default.
func detectLanguage(cwd string) string {
	checks := []struct {
		file string
		lang string
	}{
		{"package.json", "node"},
		{"pyproject.toml", "python"},
		{"requirements.txt", "python"},
		{"go.mod", "go"},
		{"Cargo.toml", "rust"},
	}
	for _, c := range checks {
		if _, err := os.Stat(filepath.Join(cwd, c.file)); err == nil {
			return c.lang
		}
	}
	return "node"
}
